name: Terraform CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # 👇 NEW: Spin up a local Linux K8s cluster (KinD) on the GitHub runner
      - name: Create KinD Cluster
        uses: helm/kind-action@v1.10.0
        with:
          cluster_name: mlops-ci
          # This automatically sets the runner's current-context to 'kind-mlops-ci'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      # 1. ON PULL REQUEST: Just show the plan
      - name: Terraform Plan (PR)
        if: github.event_name == 'pull_request'
        run: terraform plan -no-color

      # 2. ON MERGE TO MAIN: Actually apply the changes
      - name: Terraform Apply (Main)
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -parallelism=1 -auto-approve 